services:
  app:
    image: 596776566549.dkr.ecr.ap-northeast-2.amazonaws.com/pickleplay/prod:latest
    env_file:
      - .env
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      PORT: "3000"
